var codecs = ['Speex Narrowband (8 kHz)','Speex Wideband (16 kHz)','Speex Ultra-Wideband (32 kHz)','CELT Mono (48 kHz)','Opus Voice','Opus Musik'];
var ping1_time, server_selected, channel_list,channel_info,client_info, client_list,selected_client=0,selected_channel=0,loginc=[];
var properties_cl =['client_unique_identifier','client_nickname','client_version','client_platform','client_input_muted','client_output_muted',
    'client_input_hardware','client_output_hardware','client_default_channel','client_login_name','client_database_id','client_channel_grou_id',
    'client_server_groups','client_created','client_lastconnected','client_totalconnections','client_away','client_away_message','client_type',
    'client_flag_avatar','client_talk_power','client_talk_request','client_talk_request_msg','client_is_talker','client_month_bytes_downloaded',
    'client_month_bytes_uploaded','client_total_bytes_downloaded','client_total_bytes_uploaded','client_is_priority_speaker',
    'client_unread_messages','client_description','client_needed_serverquery_view_power','connection_filetransfer_bandwidth_sent',
    'connection_filetransfer_bandwidth_receieved','connection_packets_sent_total','connection_bytes_sent_total','connection_bytes_received_total',
    'connection_bandwidth_sent_last_second_total','connection_bandwidth_recieved_last_second_total','connection_bandwidth_sent_last_minute_total',
    'connection_bandwidth_received_last_minute_total','connection_client_ip','client_is_channel_commander','client_icon_id','client_country'];
var properties_cl_c =['client_nickname','client_is_talker','client_is_channel_commander','client_icon_id'];
var properties_ch = ['channel_name','channel_topic','channel_description','channel_password','channel_flag_password','channel_codec', //missing extra properties new version os TS has
    'channel_codec_quality','channel_maxclients','channel_maxfamilyclients','channel_order','channel_flag_permanent',
    'channel_flag_semi_permanent','channel_flag_temporary','channel_flag_default','channel_flag_maxclients_unlimited',
    'channel_flag_maxfamilyclients_unlimited','channel_maxfamilyclients_inherited','channel_needed_talk_power','channel_name_phonetic',
    'channel_filepath','channel_forced_silence','channel_icon_id','channel_codec_is_unencrypted','pid','channel_cid'];
var properties_ch_i = ['channel_codec','channel_codec_quality','channel_maxclients','channel_maxfamilyclients','channel_order',
    'channel_maxfamilyclients_inherited','channel_needed_talk_power','channel_name_phonetic','channel_icon_id','pid'];
var properties_ch_b = ['channel_flag_password','channel_flag_permanent','channel_flag_semi_permanent','channel_flag_temporary',
    'channel_flag_default','channel_flag_maxclients_unlimited','channel_flag_maxfamilyclients_unlimited',
    'channel_flag_maxfamilyclients_inherited','channel_codec_is_unencrypted'];
//var english = {'cid':'Channel ID'};
var english = {'access':"Access",'action':"Action",'add':"Add",'addban':"Ban Add",'addchannelgroup':"Channel Group Add",'addclient':"Add Client",'addservergroup':"Server Group Add",'admin':"Admin",
'administration':"Administration",'alreadylogin':"You are already logged in.",'antiflood':"Anti Flood",'autoban':"Autoban",'autobancount':"Autoban Count",'autobantime':"Autoban Time",
'autorefresh':"Auto refresh",'autostart':"Autostart",'away':"Away",'backup':"Backup",'ban':"Ban",'banaddok':"Ban successfully add.",'banallclients':"Ban all clients",
'banclientsbycgroup':"Ban clients by channel group",'banclientsbysgroup':"Ban clients by server group",'bandelok':"Ban successfully deleted.",'bandwidthlastminute':"Bandwidth Last Minute",
'bandwidthlastsecond':"Bandwidth Last Second",'banfrom':"Ban from",'banid':"Ban Id",'banlist':"Ban List",'banmsg':"Ban message",'bans':"Bans",'bansexport':"Bans Export",
'bansexportdesc':"To export the ban list copy the content of the box and paste it into the console.",'bantime':"Ban time",'basics':"Basics",'before':"Before",
'bytestransfered':"Bytes Transfered",'chanadmingroup':"Channel Admin Group",
'chanbackdesc':"To create a channels backup, you must click on Create.<br />It will be create a .txt file on \"site/backups/channel\" which contains the channel backup<br /><br />If you click on view you can see how the channel looks after uploading the backup.<br /><br />Deploy a backup is automatic when you click on \"Deploy\".<br />",
'chanbackupcreate':"Channel backup successfully created",'chanbackupcreateerror':"Failed to create backups of the Channel",'chanbackupdel':"Channel backup successfully deleted",
'chanbackupdelerror':"Failed to delete the channel backup",'chanbackupdeploy':"Channel backup successfully deployed",'chanbackupdeployerror':"Failed to deploy backups of the channel",
'chanbackups':"Channel Backups",'chanclientperms':"Channel-Client Permissions",'channel':"Channel",'channelcreatedok':"Channel created successfully.",'channeldelok':"Channel successfully deleted",
'channeledit':"Channel Edit",'channeleditok':"Channel successfully edited.",'channelgroup':"Channel Group",'channelgroups':"Channel Groups",'channelid':"Channel Id",'channelinfo':"Channel Info",
'channellist':"Channel List",'channelmove':"Channel Move",'channelmoveok':"Channel moved successfully.",'channelname':"Channel Name",'channelnameeditok':"Channel Name successfully edited.",
'channelpassword':"Channel Password",'channelperm':"Channel Permissions",'channelview':"Channel View",'chanorder':"Channel Order",
'checkgroupsprotected':"No delete clients which are on this groups!",'chosechanclient':"Chose Client and Channel",'cldbid':"Client Db Id",'clean':"Clean",'clid':"Client Id",'client':"Client",
'clientaddok':"Client successfully added.",'clientbanok':"Client succesfully baned.",'clientcleaner':"Client Cleaner",'clientcounter':"Client Counter",'clientdbid':"Client Db Id",
'clientdeletedok':"Client successfully deleted.",'clientkickok':"Client succesfully kicked.",'clientlist':"Client List",'clientmoveok':"Client moved successfully.",'clientname':"Client Name",
'clientpokeok':"Client succesfully poked.",'clientremoveok':"Client successfully removed.",'clients':"Clients",'clientsdimm':"Clients lowered by priority speaker",'clientsexport':"Clients Export",
'clientsexportdesc':"To export the clients from that server to another, enter the new server ID at the bottom and press \"Clients Export\".<br />You get a download of an. \"Sql\" file which contains the clients data (Groups must be new set).<br />This must just be imported into the database.",
'codec':"Codec",'codec0':"Speex Narrowband (8 kHz)",'codec1':"Speex Wideband (16 kHz)",'codec2':"Speex Ultra-Wideband (32 kHz)",'codec3':"CELT Mono (48 kHz)",'codec4':"Opus Voice",
'codec5':"Opus Musik",'codecencryptionmode':"Codec encryption mode",'codecencryptionmodeindi':"Configure per Channel",'codecencryptionmodegon':"Globally On",'codecencryptionmodegoff':"Globally Off",
'codecquality':"Codec Quality",'codecunencrypted':"Codec unencrypted",'comparator':"Comparator",'complaindel':"Complain successfully deleted",'complainlist':"Complain List",
'complainsdel':"Complains successfully deleted",'copypermsfrom':"Copy perms from",'countcomplain':"have %d complains",'countdelclients':"There have been deleted %d clients",
'countdelicon':"It were deleted %d old icons.",'countnewicon':"It were downloaded %d new icons.",'create':"Create",'createachannel':"Create a Channel",'createchanbackup':"Create Channel Backup",
'createchannel':"Create Channel",'created':"Created",'createdir':"Folder created",'createfolder':"Create folder",'createnewserver':"Create a new Virtual Server",'createserver':"Create Server",
'createserverbackup':"Create Server Backup",'createserverdesc':"It must specify a server name, the remaining values are optional.<br />Fields left blank, the default settings are used!",
'createtoken':"Create Token",'date':"Date",'days':" Days",'dbid':"Db Id",'debug':"Debug",'default':"Default",'defaultnopw':"Default channel can not have a password.",'delall':"Delete all",
'delete':"Delete",'deleteallclientsoffline':"Delete all my clients that are offline more than ",'deleteallclientsoffline2':" days offline!",
'deletemsgchannel':"Do you really want to delete this channel?",'deletemsgchannelgroup':"Do you really want to delete this channel group?",
'deletemsgclient':"Do you really want to delete this client?",'deletemsgserver':"Do you really want to delete this server?",'deletemsgservergroup':"Do you really want to delete this server group?",
'deploy':"Deploy",'description':"Description",'downbandlimit':"Download Bandwidth Limit",'downloadquota':"Download Quota",'duration':"Duration",'edit':"Edit",
'editincomplete':"Server edit incomplete",'editor':"Editor",'editperms':"Edit Perms",'enforcement':"Enforcement",'error':"Error",'error_file_alone':"The file can not be executed alone.",
'errorchannellist':"Error retrieving the channel list:",'exactly':"Exactly",'execute':"Execute",'familyclients':"Family Clients",'fdelok':"File deleted",'fileadd':"File successfull uploaded",
'filelist':"File List",'filetransfer':"File Transfer",'filetransferbandwidth':"File transfer bandwidth",'filetransport':"Filetransfer Port",'filter':"Filter",'forcedsilence':"Forced silence",
'ftconerr':"Connection to the filetransfer server failed.",'ftiniterr':"Can't initialize file download or port",'global':"Global",'grant':"Grant",'group':"Group",
'groupcreatedok':"Group successfully created.",'groupmember':"Group member",'groupnameeditok':"Group name successfully edited.",'groupnameempty':"The group name must not be empty.",
'groupremoveok':"Group successfully removed.",'groups':"Groups",'host':"Host",'hostbannerintval':"Host Banner Interval",'hostbannerurl':"Host Banner Url",'hostbuttongfx':"Host Button GFX Url",
'hostbuttontooltip':"Host Button Tooltip",'hostbuttonurl':"Host Button Url",'hostlogin':"Host Login",'hostmessage':"Host message",'hostmessageshow':"Host message show",'hosturl':"Host Url",
'hours':" Hours",'iconadd':"Icon successfully added!",
'iconfoldererr':"Error by create a folder on the icons directory this may lie on:<br /> Safemode On<br />chmod from icons folder not 777<br />User from folder not the webserver user.",
'iconerr':"Can't create or open \"icons/%s-%s/%s\"",'iconid':"Icon Id",'iconmaxsize':"The icon must have a maximum of 16 * 16 pixels!",
'iconupinfo':"Here you can upload icons to the server, note that icons no be wider or higher as 16px!",'iconupload':"Icon upload",'id':"Id",'id1':"Id 1",'id2':"Id 2",'idle':"Idle",
'incoming':"Incoming",'info':"Info",'information':"Information",'inherited':"Inherited",'inputbox':"Input Box",'instance':"Instance",'instancebackup':"Instance Server Backup",
'instanceedit':"Instance Edit",'instancetraffic':"Instance Traffic",'invokername':"Invoker Name",'invokeruid':"Invoker Uid",'ip':"Ip",'kick':"Kick",'kickallclients':"Kick all clients",
'kickclientsbycgroup':"Kick clients by channel group",'kickclientsbysgroup':"Kick clients by server group",'kickfrom':"Kick from",'kickmsg':"Kick message",'last':"Last",'lastonline':"Last Online",
'later':"Later",'length':"Length",'level':"Level",'like':"like",'limit':"Limit",'logchannel':"Log Channel",'logclient':"Log Client",'logfiletransfer':"Log Filetransfer",'login':"Login",
'loginerror':"Username or password incorrect.",'logintoqry':"Login to Server Query",'logintowi':"Login to Web Interface",'logout':"Logout",'logpermissions':"Log Permissions",'logquery':"Log Query",
'logs':"Logs",'logserver':"Log Server",'logview':"Log View",'mainchannel':"Mainchannel",'massaction':"Mass Action",'massban':"Mass Ban",'masskicker':"Mass Kicker",'massmover':"Mass Mover",
'maxclients':"Max. Clients",'maxdownbandwidth':"Max. Download Bandwidth",'maxfamilyclients':"Max Family Clients",'maxfamilyclientsinherited':"Max Family Clients Inherited",
'maxreservedslots':"Number of reserved slots",'maxupbandwidth':"Max. Upload Bandwidth",'message':"Message",'minclientschan':"Min. number of clients in the channel to force for silence",
'minclientversion':"Min. Client Version",'minutes':" Minutes",'modalandexit':"Modal message and exit",'modify':"Modify",'motd':"Message of the day",'move':"Move",
'moveallclients':"Move all clients",'moveclientsbycgroup':"Move clients by channel group",'moveclientsbysgroup':"Move clients by server group",'movefrom':"Move from",'moveto':"Move to",
'msgsendok':"Message sent successfully.",'msgtoall':"Send message to all server.",'msgtoserver':"Send message to server.",'name':"Name",'neededtalkpower':"Needed Talk Power",'negated':"Negated",
'newpassword':"New Password",'next':"Next",'nickname':"Nickname",'no':"No",'nochannel':"It must be given a Channel if tokentype=1",'nohoster':"You are not authorized to see this site.",
'nomaxclients':"Max Clients must be specified.",'nomessage':"No message",'nopermissions':"You don't have the Permission to see this infos!",'nopermsfound':"No Permissions found",'normal':"Normal",
'normallogin':"Normal Login",'noserver':"No servers available.",'noservername':"Server name must be specified.",'noserverport':"Server port must be specified.",
'notapic':"There must be a picture uploaded!",'nouse':"You do not have permission to use the \"use\" command!",'number':"Number",'offline':"Offline",'online':"Online",
'onlinevirtual':"Online Virtual",'option':"Option",'options':"Options",'outgoing':"Outgoing",'outputbox':"Output Box",'overwritegroup':"Overwrite from",'packetstransfered':"Packets Transfered",
'pagenotfound':"Page not found!",'pagenotfoundmsg':"The selected page was not found.",'password':"Password",'passwordset':"Password Set",'passwordsetok':"Password successfully set.",
'permanent':"Permanent",'permexdesc':"To export permissions, select a source type (group/channel/client), then enter the id of the source.<br />Now, they specify what should be the target type (group / channel / client) and also give here the id of the target.<br /><br />After you click \"view\" they have shown one or more commands.<br />This you must copy and paste it on your target server in the console.<br />",
'permexport':"Permission Export",'permid':"Perm Id",'permissionlist':"Permission List",'permname':"Permission Name",'phoneticname':"Phonetic Name",'pid':"Pid",'platform':"Platform",
'pointsneededblockcmd':"Points needed to block commands",'pointsneededblockip':"Points needed to block IP",'pointstickreduce':"Reduced points per tick",'pointsneededwarning':"Points needed warning",
'pointsneededkick':"Points needed kick",'pointsneededban':"Points needed ban",'pointsbantime':"Points ban time",'poke':"Poke",'pokemsg':"Poke message",'port':"Port",'query':"Query",
'queryclients':"Query Clients",'queryconsole':"Query Console",'questsquerygroup':"Guest Server Query Group",'reason':"Reason",'removetime':"Remove Time",'rename':"Rename",'runtime':"Runtime",
'savedb':"Save Db",'search':"Search",'searchfor':"Search for ",'seconds':" Seconds",'securitylevel':"Security level",'select':"Select",'selectall':"Select all",'semipermanent':"Semi Permanent",
'send':"Send",'server':"Server",'serveraddress':"Server address",'serverbackups':"Server Backups",'serverbackdelerr':"Failed to delete the server backups.",
'serverbackdelok':"Serverbackup successfully deleted.",'serverbackdeployok':"Serverbackup successfully deployed.",
'servbackdesc':"To create a server backup, you must click on Create.<br />It will be create a .txt file on \"site/backups/server\" which contains the server backup<br /><br />Deploy a backup is automatic when you click on \"Deploy\".<br />",
'serverbackupok':"Serverbackup from %s:%s successfully created.",'serverbackuperr':"Serverbackup from %s:%s not created.",'serverdelok':"Server succesfully deleted.",'serveredit':"Server Edit",
'servereditok':"Server successfully edited.",'servergroup':"Server Group",'servergroups':"Server Groups",'serverid':"Server Id",
'serverlist':"Server List",'serverlistcallerr':"Coud not called the serverlist",'serveroffline':"Server offline!",'serveroffmsg':"The specified server-query is currently not available.",
'serverpassword':"Server Password",'serverstartok':"Server successfully started.",'serverstats':"There are %d servers with %d slots. Of these, %d slots are filled.",
'serverstopok':"Server stopped successfully.",'serverupdateav':"Update available to ",'serverview':"Server View",'set':"Set",'settings':"Settings",'showgrantedonly':"Show granted only",
'showmessagelog':"Show message in log",'showmodalmessage':"Show modal message",'showmoreentrys':"Show more entrys",'showonweblist':"Show server on weblist",'size':"Size",'skip':"Skip",
'snapwarning':"Regard!<br />If you are uploading a server backup to a virtual server while the server from which the backup is still running, this causes continuously a crash, if both server simultaneously running!",
'sourceid':"Source id",'sourcenick':"Source nick",'sourcetype':"Source type",'squerybantime':"Server Query Ban Time",'squeryfloodcmd':"Server Query Flood Command",
'squeryfloodtime':"Server Query Flood Time",'standardgroups':"Standard Groups",'start':"Start",'status':"Status",'stop':"Stop",'stoprefresh':"Stop refresh",
'stopservermsg':"Do you really want to stop this server?",'switch':"Switch",'talkpower':"Talk Power",'targetid':"Target id",'targetnick':"Target nick",'targettype':"Target type",
'tempcadmingroup':"Template Channel Admin Group",'tempcdefgroup':"Template Channel Default Group",'template':"Template",'temporary':"Temporary",'temppw':"Temporary Password",
'temppwcnoerr':"Temporary Password successfully created.",'temppwdnoerr':"Temporary Password successfully deleted.",'tempsadmingroup':"Template Server Admin Group",
'tempsdefgroup':"Template Server Default Group",'thismonth':"This Month",'thisweek':"This Week",'time':"Time",'today':"Today",'token':"Token",'tokencreatedok':"Token successfully created.",
'tokendeleteok':"Token successfully deleted.",'tokenlist':"Token List",'topic':"Topic",'total':"Total",'totalsize':"Total size",'transfers':"Transfers",
'tsviewpubhtml':"Copy and paste the html code in an external html file where it will display the Ts-Viewer:",'type':"Type",'uniqueid':"Unique Id",'unlimited':"Unlimited",
'upbandlimit':"Upload Bandwidth Limit",'upload':"File upload",'UPLOAD_ERR_INI_SIZE':"The uploaded file exceeds the upload_max_filesize directive in php.ini.",
'UPLOAD_ERR_FORM_SIZE':"The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.",'UPLOAD_ERR_PARTIAL':"The uploaded file was only partially uploaded.",
'UPLOAD_ERR_NO_FILE':"No file was uploaded.",'uploadquota':"Upload Quota",'username':"Username",'value':"Value",'version':"Version",'view':"View",'virtualserver':"Virtual Server",
'virtualservermanagement':"Virtual Server Management",'virtualtraffic':"Server Traffic",'warning':"Warning",'welcomemsg':"Welcome message",'yes':"Yes"};